# Generated by Django 4.0.1 on 2022-01-19 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.DateTimeField(auto_now_add=True)),
                ('value', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
